services:
  main-server:
    build: .
    ports:
      - 8080:8080
    depends_on:
      mysql-db:
        condition: service_healthy
      redis-cache-server:
        condition: service_healthy
      redis-token-server:
        condition: service_healthy


  mysql-db:
    image: mysql:8.4.5
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: zypt
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      retries: 10

  redis-cache-server:
    image: redis
    ports:
      - 6380:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10

  redis-token-server:
    image: redis
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 10