spring:
  application:
    name: ZyptApiServer

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/livekit
    username: root
    password: 1234



  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update


  # redis config
  data:
    redis:
      host: localhost
      port: 6379


livekit:
  api-key: APIW8s72Jf9nQ5S
  secret-key: Z6svQ2YQTlXS8q2Zk5LEUfhpVeP13FSxboE9GwsNVIE
  URL: "https://studytracking-4o27wuve.livekit.cloud"


jwt :
  SECRET_KEY : 32rmfwkfmf**ak#wcn!jdigkrld$psksmsak@wcnjqhs#ek$rhgksek(fnfnfnf
  ACCESS_TOKEN_EXPIRATION : 43200000    # 12hour milliseconds
  REFRESH_TOKEN_EXPIRATION : 1209600000 # 14days
